### ISSUE TITLE
String() is not displaying wildcards

### ISSUE THREAD

**Issue by ThomasSchwarzBT-VS** [becheran/wildmatch-go#1]
Hi Armin :-)
just noticed, that wildcards are not included at the String() method.
Is would consider this as a bug or is it intended for some reason?

This snippet prints `Output: ''`

```
import (
	"fmt"
	"github.com/becheran/wildmatch-go"
)

func main() {
	m := wildmatch.NewWildMatch("*")
	fmt.Println(fmt.Sprintf("Output: '%s'", m.String()))
}
```

**Comment by becheran** [comment]
Yes. This is definitely a bug. Thanks for reporting Thomas. :-)

I fixed it and pushed a new version `2.0.1` which fixes the issue.

Though, there is still another bug that some (rather complex) patterns won't be matched correctly. Will update this go lib once I find the time. See issue #2
